### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by yairdata** [jpmml/pyspark2pmml#21] opened 2019-06-17 15:49 UTC
i run with pyspark 2.4.3
               jpmml-sparkml-executable-1.5.1.jar
i load the jar with:

`import os
os.environ['PYSPARK_SUBMIT_ARGS'] = '--jars jpmml-sparkml-executable-1.5.1.jar pyspark-shell'`
when i get to this line:
pmmlBuilder = PMMLBuilder(spark.sparkContext, df, model)
i get :
`C:\FAST\anaconda\python36\win64\431\lib\site-packages\pyspark2pmml\__init__.py in __init__(self, sc, df, pipelineModel)
     10                 javaSchema = javaDf.schema.__call__()
     11                 javaPipelineModel = pipelineModel._to_java()
---> 12                 javaPmmlBuilder = sc._jvm.org.jpmml.sparkml.PMMLBuilder(javaSchema, javaPipelineModel)
     13                 if(not isinstance(javaPmmlBuilder, JavaObject)):
     14                         raise RuntimeError("JPMML-SparkML not found on classpath")

TypeError: 'JavaPackage' object is not callable`
is it because of version issues ? other staff ?

**Comment by vruusmann** [comment] 2019-06-17 17:02
Exact duplicate of https://github.com/jpmml/pyspark2pmml/issues/17

> is it because of version issues ?

You're experiencing all sorts of issues, because you use outdated versions. Next time, before opening an issue, upgrade your versions to the latest, and see if the issue is a real one.

**Closed as completed by vruusmann** 2019-06-17 17:02 UTC

**Comment by yairdata** [comment] 2019-06-17 17:33
which outdated versions....
i now used also used jpmml-sparkml 1.5.3 version and it aligned exactly with the readme .
2.4.X | master | 1.5.3
got the same problem.
so i guess it's not version issue.

**Comment by vruusmann** [comment] 2019-06-17 17:52
> which outdated versions....

The above exception is raised by the Python code of the PySpark2PMML package. You need to update both Java backend and Python frontend.

**Comment by yairdata** [comment] 2019-06-17 18:03
i understand , but i have to use the pyspark2pmml 0.5.0 version since i must use pip install from pypi becuase of different restrictions, so i can't upgrade it until the latest version will get there.
for that version i see in the releases tab it should work with 1.4.10 for spark 2.3.x version , and with 1.5.3 for 2.4.x version, and this is what i am testing with and fails.
am i correct ?

**Comment by vruusmann** [comment] 2019-06-17 18:20
> i have to use the pyspark2pmml 0.5.0 version since i must use pip install from pypi 

There's PySpark2PMML version 0.5.1 available in PyPI currently. And the 0.5.1 version includes this JPMML-SparkML classpath diagnostics fix.

> i see in the releases tab it should work with 1.4.10 for spark 2.3.x version , and with 1.5.3 for 2.4.x version, and this is what i am testing with and fails.

Rule no 1: always use the latest PySpark2PMML frontend; this one frontend will work with all JPMML-SparkML backends. PySpark2PMML is not updated very frequently, maybe once every three months.

Rule no 2: always use the latest JPMML-SparkML backend; the backend is Apache Spark version specific; if you attempt to pair JPMML-SparkML with a worng Apache Spark version you will get an exception. JPMML-SparkML is updated more frequently, maybe once per month or so.

> this is what i am testing with and fails.

Right now, your testing fails, because you don't have a JPMML-SparkML library available on Apache Spark classpath. This topic is already discussed in #17, and I have nothing to add to it.

Maybe there are other issues with your Apache Spark application code. But we have no way of knowing, before you fix your classpath first.

**Comment by yairdata** [comment] 2019-06-17 18:47
now i got it to work on one case, pyspark2pmml 0.5.0 version with jpmml-sparkml 1.5.3 and spark 2.4.3 , but according to the changelog it should have worked with 1.5.1 version in 0.5.0 version....
so i wonder if the jars in the release keeps updating... the classpath is not the issue since with certain versions it does work.
i will download the latest python and jpmml-sparkml and try again , since i need it to work also in spark 2.3.0 , which currently doens't work with 0.5.0 version and jpmml-sparkml versions 1.4.10 and 1.4.8

**Comment by vruusmann** [comment] 2019-06-17 19:05
> since i need it to work also in spark 2.3.0 

That would be PySpark2PMML version 0.5.1 plus JPMML-SparkML version 1.4.10.

If you come and report a "bug" based on some other version combination, you will be blocked.
