### ISSUE TITLE
SLF4J: Class path contains multiple SLF4J bindings.

### ISSUE THREAD

**Issue by yuanbianGit** [jpmml/pyspark2pmml#34] opened 2021-04-26 06:25 UTC
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/BigData/spark/jars/jpmml-sparkml-executable-1.5.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/BigData/hadoop/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]

**Comment by vruusmann** [comment] 2021-04-26 16:08
Closing as exact duplicate of https://github.com/jpmml/jpmml-sparkml/issues/111

**Closed as completed by vruusmann** 2021-04-26 16:08 UTC
